### ISSUE TITLE
Regression of Freemarker <?TEMPLATE-SPLIT-PI?> processing instruction

### ISSUE THREAD

**Issue by gperry100** [smooks/smooks-templating-cartridge#55]
When using version 2.0.0-M3 of Smooks with Freemarker and the <?TEMPLATE-SPLIT-PI?> processing instruction, the follow error message is received:

`org.smooks.api.SmooksException: Failed to filter source`

Example simple use-case project attached demonstrating issue:

[smooks-json-to-xml-using-freemarker.zip](https://github.com/smooks/smooks-templating-cartridge/files/6614860/smooks-json-to-xml-using-freemarker.zip)

Original issue raised in google groups forum for Smooks users.

https://groups.google.com/g/smooks-user/c/4EuvRYWvUX8/m/5_j6w6v0CwAJ

**Comment by claudemamo** [comment]
As noted in the discussion, this is caused by a regression in `<?TEMPLATE-SPLIT-PI?>`. Having said this, I don't see much point in supporting this processing instruction anymore since you should easily achieve what you want with [pipelines](https://github.com/smooks/smooks#pipeline). I'll add a migrate note to indicate that `<?TEMPLATE-SPLIT-PI?>` is no longer supported and pipelines should be used instead.

**Comment by claudemamo** [comment]
As noted in the discussion, this is caused by a regression in `<?TEMPLATE-SPLIT-PI?>`. Having said this, I don't see much point in supporting this processing instruction anymore since you should easily achieve what you want with [pipelines](https://github.com/smooks/smooks#pipeline). I'll add a migrate note to indicate that `<?TEMPLATE-SPLIT-PI?>` is no longer supported and pipelines should be used instead.
